### PR TITLE
Upgrade SDK for esp8266, use common library versions for all targets

### LINKED ISSUE #359: Request: use WiFiManager v2.0.17
Currently, the esp32 target is using WiFiManager `v2.0.15-rc.1` while esp8266 is stuck with `0.16.0` for some reason.
The library supports both platforms officially and there's been a new release not that long ago:
https://github.com/tzapu/WiFiManager/releases/tag/v2.0.17

The proposal is to use the latest version across all targets.

I don't have all board types on my hands to test the changes so want to discuss it here first. Is there a reason for an ancient version of WiFiManager to be used for esp8266?

### PR DESCRIPTION
**Pull request by jekader**
This PR fixes #359 which required also bumping the SDK version for esp8266 to the latest version supported by PlatformIO and adjusting the code base accordingly.

Notable changes:
* `espressif8266 4.2.1` core used
* `EspSoftwareSerial 8.2.0` used for all targets
* `WiFiManager v2.0.17` used for all targets
* `Hash_tng` used for all targets since the code is mostly identical to `mr-glt/SHA-1`
* `ColorConverter` removed due to bugs, `RgbToHex` and `HexToRgb` functions re-created locally
* `webSocket.sendTXT` invocations fixed due to compiler errors on new SDK

Tested to work on a esp8266 board and an Ulanzi clock

### CODE REVIEW

**Comment by foorschtbar** [comment]
My two ESP8266 (D1 Mini) PixelIts run fine, but two beta testers had these gliches. Any idea!?

https://github.com/user-attachments/assets/f6b7eb7f-d0e5-454c-86f5-e0f9c51f1519

**Comment by jekader** [comment]
Hmm, very interesting. I saw similar glitches before when porting to ESP32-C3 and those were related to some timing bugs in FastLED. Another less likely cause could be the matrix pin also being mapped to something else (sensor/UART) sending data and corrupting the display.

We might need to gather some details about faulty devices to find out why the same binary would work on some devices yet glitch on others.

I attached a MicroMatrix to my esp8266 board and do not see any glitches yet, however I'm also facing issues with pixelit-projekt.de returning NXDOMAIN and the UI does not load so can't test much further.

**Comment by foorschtbar** [comment]
The DNS problem with pixelit-projekt.de should be fixed after flushing your DNS. A added the domain as replacement for the github.io domain a few minutes ago

Do you want to join our development discord or telegram group?

**Comment by jekader** [comment]
Thanks, JS artifacts load up fine now. I'll join the pixelitdisplay channel on Telegram so that we can do more testing.

I'm seeing a strange artifact on the esp8266 where the clock does not refresh the LED matrx while showing up fine on the LiveView while other functions such as sending text via JSON show up fine.

**Comment by foorschtbar** [comment]
mention me in telegram, i add you to the private development group

**Pull request merged**
